import { map } from "nanostores";

export const promptDefines = [
  {
    prompt: `aqua eyes`,
    categories: [`eyes-color`],
    isEnableByDefault: false,
    colorCategory: `eyes-color`,
    color: `aqua`,
    suggests: null,
    parent: null,
  },
  {
    prompt: `black eyes`,
    categories: [`eyes-color`],
    isEnableByDefault: false,
    colorCategory: `eyes-color`,
    color: `black`,
    suggests: null,
    parent: null,
  },
  {
    prompt: `blue eyes`,
    categories: [`eyes-color`],
    isEnableByDefault: false,
    colorCategory: `eyes-color`,
    color: `blue`,
    suggests: null,
    parent: null,
  },
  {
    prompt: `brown eyes`,
    categories: [`eyes-color`],
    isEnableByDefault: false,
    colorCategory: `eyes-color`,
    color: `brown`,
    suggests: null,
    parent: null,
  },
  {
    prompt: `green eyes`,
    categories: [`eyes-color`],
    isEnableByDefault: false,
    colorCategory: `eyes-color`,
    color: `green`,
    suggests: null,
    parent: null,
  },
  {
    prompt: `grey eyes`,
    categories: [`eyes-color`],
    isEnableByDefault: false,
    colorCategory: `eyes-color`,
    color: `grey`,
    suggests: null,
    parent: null,
  },
  {
    prompt: `orange eyes`,
    categories: [`eyes-color`],
    isEnableByDefault: false,
    colorCategory: `eyes-color`,
    color: `orange`,
    suggests: null,
    parent: null,
  },
  {
    prompt: `purple eyes`,
    categories: [`eyes-color`],
    isEnableByDefault: false,
    colorCategory: `eyes-color`,
    color: `purple`,
    suggests: null,
    parent: null,
  },
  {
    prompt: `pink eyes`,
    categories: [`eyes-color`],
    isEnableByDefault: false,
    colorCategory: `eyes-color`,
    color: `pink`,
    suggests: null,
    parent: null,
  },
  {
    prompt: `red eyes`,
    categories: [`eyes-color`],
    isEnableByDefault: true,
    colorCategory: `eyes-color`,
    color: `red`,
    suggests: null,
    parent: null,
  },
  {
    prompt: `white eyes`,
    categories: [`eyes-color`],
    isEnableByDefault: false,
    colorCategory: `eyes-color`,
    color: `white`,
    suggests: null,
    parent: null,
  },
  {
    prompt: `yellow eyes`,
    categories: [`eyes-color`],
    isEnableByDefault: false,
    colorCategory: `eyes-color`,
    color: `yellow`,
    suggests: null,
    parent: null,
  },
  {
    prompt: `tsurime`,
    categories: [`eyes-shape`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: null,
  },
  {
    prompt: `tareme`,
    categories: [`eyes-shape`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: null,
  },
  {
    prompt: `thick eyebrows`,
    categories: [`eyebrows-shape`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: null,
  },
  {
    prompt: `eyelashes`,
    categories: [`eyelashes`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: null,
  },
  {
    prompt: `long eyelashes`,
    categories: [`eyelashes`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: `eyelashes`,
  },
  {
    prompt: `thick eyelashes`,
    categories: [`eyelashes`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: `eyelashes`,
  },
  {
    prompt: `aqua hair`,
    categories: [`hair-color`],
    isEnableByDefault: false,
    colorCategory: `hair-color`,
    color: `aqua`,
    suggests: [`blue hair`, `green hair`],
    parent: null,
  },
  {
    prompt: `black hair`,
    categories: [`hair-color`],
    isEnableByDefault: false,
    colorCategory: `hair-color`,
    color: `black`,
    suggests: [`brown hair`, `blue hair`, `grey hair`],
    parent: null,
  },
  {
    prompt: `blonde hair`,
    categories: [`hair-color`],
    isEnableByDefault: true,
    colorCategory: `hair-color`,
    color: `blonde`,
    suggests: [`orange hair`, `brown hair`],
    parent: null,
  },
  {
    prompt: `blue hair`,
    categories: [`hair-color`],
    isEnableByDefault: false,
    colorCategory: `hair-color`,
    color: `blue`,
    suggests: [`aqua hair`, `purple hair`],
    parent: null,
  },
  {
    prompt: `light blue hair`,
    categories: [`hair-color`],
    isEnableByDefault: false,
    colorCategory: `hair-color`,
    color: `light-blue`,
    suggests: [`aqua hair`],
    parent: null,
  },
  {
    prompt: `dark blue hair`,
    categories: [`hair-color`],
    isEnableByDefault: false,
    colorCategory: `hair-color`,
    color: `dark-blue`,
    suggests: [`black hair`],
    parent: null,
  },
  {
    prompt: `brown hair`,
    categories: [`hair-color`],
    isEnableByDefault: false,
    colorCategory: `hair-color`,
    color: `brown`,
    suggests: [`black hair`, `orange hair`, `red hair`],
    parent: null,
  },
  {
    prompt: `light brown hair`,
    categories: [`hair-color`],
    isEnableByDefault: false,
    colorCategory: `hair-color`,
    color: `light-brown`,
    suggests: [`blonde hair`, `brown hair`],
    parent: null,
  },
  {
    prompt: `green hair`,
    categories: [`hair-color`],
    isEnableByDefault: false,
    colorCategory: `hair-color`,
    color: `green`,
    suggests: [`aqua hair`],
    parent: null,
  },
  {
    prompt: `dark green hair`,
    categories: [`hair-color`],
    isEnableByDefault: false,
    colorCategory: `hair-color`,
    color: `dark-green`,
    suggests: [`green hair`],
    parent: null,
  },
  {
    prompt: `light green hair`,
    categories: [`hair-color`],
    isEnableByDefault: false,
    colorCategory: `hair-color`,
    color: `light-green`,
    suggests: [`green hair`],
    parent: null,
  },
  {
    prompt: `grey hair`,
    categories: [`hair-color`],
    isEnableByDefault: false,
    colorCategory: `hair-color`,
    color: `grey`,
    suggests: [`white hair`, `black hair`],
    parent: null,
  },
  {
    prompt: `orange hair`,
    categories: [`hair-color`],
    isEnableByDefault: false,
    colorCategory: `hair-color`,
    color: `orange`,
    suggests: [`brown hair`, `red hair`],
    parent: null,
  },
  {
    prompt: `pink hair`,
    categories: [`hair-color`],
    isEnableByDefault: false,
    colorCategory: `hair-color`,
    color: `pink`,
    suggests: [`purple hair`, `red hair`],
    parent: null,
  },
  {
    prompt: `purple hair`,
    categories: [`hair-color`],
    isEnableByDefault: false,
    colorCategory: `hair-color`,
    color: `purple`,
    suggests: [`blue hair`, `pink hair`],
    parent: null,
  },
  {
    prompt: `light purple hair`,
    categories: [`hair-color`],
    isEnableByDefault: false,
    colorCategory: `hair-color`,
    color: `light-purple`,
    suggests: [`pink hair`, `purple hair`, `purple hair`],
    parent: null,
  },
  {
    prompt: `red hair`,
    categories: [`hair-color`],
    isEnableByDefault: false,
    colorCategory: `hair-color`,
    color: `red`,
    suggests: [`orange hair`, `brown hair`],
    parent: null,
  },
  {
    prompt: `white hair`,
    categories: [`hair-color`],
    isEnableByDefault: false,
    colorCategory: `hair-color`,
    color: `white`,
    suggests: [`grey hair`],
    parent: null,
  },
  {
    prompt: `short hair`,
    categories: [`hair-length`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: null,
  },
  {
    prompt: `medium hair`,
    categories: [`hair-length`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: null,
  },
  {
    prompt: `long hair`,
    categories: [`hair-length`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: null,
  },
  {
    prompt: `very long hair`,
    categories: [`hair-length`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: null,
  },
  {
    prompt: `absurdly long hair`,
    categories: [`hair-length`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: null,
  },

  {
    prompt: `bob cut`,
    categories: [`hair-style`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: null,
  },
  {
    prompt: `inverted bob`,
    categories: [`hair-style`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: null,
  },
  {
    prompt: `pixie cut`,
    categories: [`hair-style`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: null,
  },
  {
    prompt: `undercut`,
    categories: [`hair-style`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: null,
  },
  {
    prompt: `flipped hair`,
    categories: [`hair-style`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: null,
  },
  {
    prompt: `dreadlocks`,
    categories: [`hair-style`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: null,
  },
  {
    prompt: `hime cut`,
    categories: [`hair-style`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: [`blunt ends`],
    parent: null,
  },
  {
    prompt: `curly hair`,
    categories: [`hair-style`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: null,
  },
  {
    prompt: `drill hair`,
    categories: [`hair-style`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: null,
  },
  {
    prompt: `twin drills`,
    categories: [`hair-style`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: `drill hair`,
  },
  {
    prompt: `hair flaps`,
    categories: [`hair-style`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: null,
  },
  {
    prompt: `messy hair`,
    categories: [`hair-style`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: null,
  },
  {
    prompt: `pointy hair`,
    categories: [`hair-style`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: null,
  },
  {
    prompt: `ringlets`,
    categories: [`hair-style`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: null,
  },
  {
    prompt: `straight hair`,
    categories: [`hair-style`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: null,
  },
  {
    prompt: `wavy hair`,
    categories: [`hair-style`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: null,
  },
  {
    prompt: `hair over shoulder`,
    categories: [`hair-style`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: null,
  },

  {
    prompt: `bow-shaped hair`,
    categories: [`tied-hair`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: null,
  },
  {
    prompt: `braid`,
    categories: [`tied-hair`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: null,
  },
  {
    prompt: `braided bangs`, // TODO: front hair??
    categories: [`tied-hair`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: `braid`,
  },
  {
    prompt: `front braid`,
    categories: [`tied-hair`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: `braid`,
  },
  {
    prompt: `side braid`,
    categories: [`tied-hair`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: `braid`,
  },
  {
    prompt: `frentch braid`,
    categories: [`tied-hair`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: `braid`,
  },
  {
    prompt: `crown braid`,
    categories: [`tied-hair`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: `braid`,
  },
  {
    prompt: `single braid`,
    categories: [`tied-hair`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: `braid`,
  },
  {
    prompt: `multiple braids`,
    categories: [`tied-hair`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: `braid`,
  },
  {
    prompt: `twin braids`,
    categories: [`tied-hair`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: `braid`,
  },
  {
    prompt: `low twin braids`,
    categories: [`tied-hair`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: `braid`,
  },
  {
    prompt: `tri braids`,
    categories: [`tied-hair`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: `braid`,
  },
  {
    prompt: `flower-shaped hair`,
    categories: [`tied-hair`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: null,
  },
  {
    prompt: `hair bun`,
    categories: [`tied-hair`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: null,
  },
  {
    prompt: `braided bun`,
    categories: [`tied-hair`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: `hair bun`,
  },
  {
    prompt: `single hair bun`,
    categories: [`tied-hair`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: `hair bun`,
  },
  {
    prompt: `double bun`,
    categories: [`tied-hair`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: `hair bun`,
  },
  {
    prompt: `cone hair bun`,
    categories: [`tied-hair`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: `hair bun`,
  },
  {
    prompt: `doughnut hair bun`,
    categories: [`tied-hair`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: `hair bun`,
  },
  {
    prompt: `heart hair bun`,
    categories: [`tied-hair`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: `hair bun`,
  },
  {
    prompt: `triple bun`,
    categories: [`tied-hair`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: `hair bun`,
  },
  {
    prompt: `hair rings`,
    categories: [`tied-hair`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: null,
  },
  {
    prompt: `single hair ring`,
    categories: [`tied-hair`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: `hair rings`,
  },
  {
    prompt: `half updo`,
    categories: [`tied-hair`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: null,
  },
  {
    prompt: `one side up`,
    categories: [`tied-hair`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: null,
  },
  {
    prompt: `two side up`,
    categories: [`tied-hair`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: null,
  },
  {
    prompt: `low-braided long hair`,
    categories: [`tied-hair`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: null,
  },
  {
    prompt: `low-tied long hair`,
    categories: [`tied-hair`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: null,
  },
  {
    prompt: `mizura`,
    categories: [`tied-hair`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: null,
  },
  {
    prompt: `multi-tied-hair`,
    categories: [`tied-hair`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: null,
  },
  {
    prompt: `ponytail`,
    categories: [`tied-hair`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: null,
  },
  {
    prompt: `folded ponytail`,
    categories: [`tied-hair`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: `ponytail`,
  },
  {
    prompt: `high ponytail`,
    categories: [`tied-hair`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: `ponytail`,
  },
  {
    prompt: `short ponytail`,
    categories: [`tied-hair`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: `ponytail`,
  },
  {
    prompt: `side ponytail`,
    categories: [`tied-hair`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: `ponytail`,
  },
  {
    prompt: `split ponytail`,
    categories: [`tied-hair`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: `ponytail`,
  },
  {
    prompt: `topknot`,
    categories: [`tied-hair`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: null,
  },
  {
    prompt: `twintails`,
    categories: [`tied-hair`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: null,
  },
  {
    prompt: `low twintails`,
    categories: [`tied-hair`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: `twintails`,
  },
  {
    prompt: `short twintails`,
    categories: [`tied-hair`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: `twintails`,
  },
  {
    prompt: `tri tails`,
    categories: [`tied-hair`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: null,
  },
  {
    prompt: `ponytail`,
    categories: [`tied-hair`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: null,
  },
  {
    prompt: `high ponytail`,
    categories: [`tied-hair`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: `ponytail`,
  },

  {
    prompt: `arched bangs`,
    categories: [`front-hair`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: null,
  },
  {
    prompt: `asymmetrical bangs`,
    categories: [`front-hair`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: null,
  },
  {
    prompt: `bangs pinned back`,
    categories: [`front-hair`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: null,
  },
  {
    prompt: `blunt bangs`,
    categories: [`front-hair`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: null,
  },
  {
    prompt: `crossed bangs`,
    categories: [`front-hair`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: null,
  },
  {
    prompt: `diagonal bangs`,
    categories: [`front-hair`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: null,
  },
  {
    prompt: `blunt bangs`,
    categories: [`front-hair`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: null,
  },
  {
    prompt: `dyed bangs`,
    categories: [`front-hair`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: null,
  },
  {
    prompt: `blunt bangs`,
    categories: [`front-hair`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: null,
  },
  {
    prompt: `hair over eyes`,
    categories: [`front-hair`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: null,
  },
  {
    prompt: `hair over one eye`,
    categories: [`front-hair`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: null,
  },
  {
    prompt: `long bangs`,
    categories: [`front-hair`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: null,
  },
  {
    prompt: `parted bangs`,
    categories: [`front-hair`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: null,
  },
  {
    prompt: `curtained bangs`,
    categories: [`front-hair`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: null,
  },
  {
    prompt: `hair between eyes`,
    categories: [`front-hair`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: null,
  },
  {
    prompt: `hair intakes`,
    categories: [`front-hair`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: null,
  },
  {
    prompt: `single hair intake`,
    categories: [`front-hair`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: `hair intakes`,
  },
  {
    prompt: `blunt ends`,
    categories: [`front-hair`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: [`blunt bangs`],
    parent: null,
  },

  {
    prompt: `sidelocks`,
    categories: [`sidelocks`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: null,
  },
  {
    prompt: `asymmetrical sidelocks`,
    categories: [`sidelocks`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: `sidelocks`,
  },
  {
    prompt: `drill sidelocks`,
    categories: [`sidelocks`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: `sidelocks`,
  },
  {
    prompt: `low tied sidelocks`,
    categories: [`sidelocks`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: `sidelocks`,
  },
  {
    prompt: `single sidelock`,
    categories: [`sidelocks`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: [`asymmetrical sidelocks`, `asymmetrical hair`],
    parent: `sidelocks`,
  },
  {
    prompt: `ahoge`,
    categories: [`top-of-the-head`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: null,
  },
  {
    prompt: `heart ahoge`,
    categories: [`top-of-the-head`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: `ahoge`,
  },
  {
    prompt: `huge ahoge`,
    categories: [`top-of-the-head`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: `ahoge`,
  },
  {
    prompt: `antenna hair`,
    categories: [`top-of-the-head`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: null,
  },
  {
    prompt: `heart antenna hair`,
    categories: [`top-of-the-head`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: `antenna hair`,
  },
  {
    prompt: `hair pulled back`,
    categories: [`top-of-the-head`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: null,
  },
  {
    prompt: `hair slicked back`,
    categories: [`top-of-the-head`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: null,
  },
  {
    prompt: `alternate hairstyle`,
    categories: [`hair-misc`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: null,
  },
  {
    prompt: `hair down`,
    categories: [`hair-misc`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: null,
  },
  {
    prompt: `hair up`,
    categories: [`hair-misc`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: null,
  },

  {
    prompt: `hair ornament`,
    categories: [`hair-ornament`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: null,
  },
  {
    prompt: `hairpin`,
    categories: [`hair-ornament`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: null,
  },
  {
    prompt: `hairclip`,
    categories: [`hair-ornament`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: null,
  },
  {
    prompt: `cross hair ornament`,
    categories: [`hair-ornament`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: [`hairpin`],
    parent: `hair ornament`,
  },
  {
    prompt: `x hair ornament`,
    categories: [`hair-ornament`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: [`hairpin`],
    parent: `hair ornament`,
  },
  {
    prompt: `snowflake hair ornament`,
    categories: [`hair-ornament`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: `hair ornament`,
  },
  {
    prompt: `bat hair ornament`,
    categories: [`hair-ornament`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: `hair ornament`,
  },
  {
    prompt: `anchor hair ornament`,
    categories: [`hair-ornament`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: `hair ornament`,
  },
  {
    prompt: `bone hair ornament`,
    categories: [`hair-ornament`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: `hair ornament`,
  },
  {
    prompt: `butterfly hair ornament`,
    categories: [`hair-ornament`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: `hair ornament`,
  },
  {
    prompt: `cat hair ornament`,
    categories: [`hair-ornament`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: `hair ornament`,
  },
  {
    prompt: `character hair ornament`,
    categories: [`hair-ornament`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: `hair ornament`,
  },
  {
    prompt: `clover hair ornament`,
    categories: [`hair-ornament`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: `hair ornament`,
  },
  {
    prompt: `coin hair ornament`,
    categories: [`hair-ornament`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: `hair ornament`,
  },
  {
    prompt: `crescent hair ornament`,
    categories: [`hair-ornament`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: `hair ornament`,
  },
  {
    prompt: `cube hair ornament`,
    categories: [`hair-ornament`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: `hair ornament`,
  },
  {
    prompt: `d-pad hair ornament`,
    categories: [`hair-ornament`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: `hair ornament`,
  },
  {
    prompt: `feather hair ornament`,
    categories: [`hair-ornament`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: `hair ornament`,
  },
  {
    prompt: `fish hair ornament`,
    categories: [`hair-ornament`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: `hair ornament`,
  },
  {
    prompt: `food-themed hair ornament`,
    categories: [`hair-ornament`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: `hair ornament`,
  },
  {
    prompt: `frog hair ornament`,
    categories: [`hair-ornament`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: `hair ornament`,
  },
  {
    prompt: `hair beads`,
    categories: [`hair-ornament`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: `hair ornament`,
  },
  {
    prompt: `hair bell`,
    categories: [`hair-ornament`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: `hair ornament`,
  },
  {
    prompt: `hair bobbles`,
    categories: [`hair-ornament`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: `hair ornament`,
  },
  {
    prompt: `hair flower`,
    categories: [`hair-ornament`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: `hair ornament`,
  },
  {
    prompt: `hair scrunchie`,
    categories: [`hair-ornament`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: `hair ornament`,
  },
  {
    prompt: `hair stick`,
    categories: [`hair-ornament`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: `hair ornament`,
  },
  {
    prompt: `heart hair ornament`,
    categories: [`hair-ornament`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: `hair ornament`,
  },
  {
    prompt: `kanzashi`,
    categories: [`hair-ornament`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: `hair ornament`,
  },
  {
    prompt: `leaf hair ornament`,
    categories: [`hair-ornament`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: `hair ornament`,
  },
  {
    prompt: `monocle hair ornament`,
    categories: [`hair-ornament`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: `hair ornament`,
  },
  {
    prompt: `musical note hair ornament`,
    categories: [`hair-ornament`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: `hair ornament`,
  },
  {
    prompt: `pom pom hair ornament`,
    categories: [`hair-ornament`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: `hair ornament`,
  },
  {
    prompt: `rabbit hair ornament`,
    categories: [`hair-ornament`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: `hair ornament`,
  },
  {
    prompt: `shark hair ornament`,
    categories: [`hair-ornament`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: `hair ornament`,
  },
  {
    prompt: `skull hair ornament`,
    categories: [`hair-ornament`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: [`bone hair ornament`],
    parent: `hair ornament`,
  },
  {
    prompt: `snake hair ornament`,
    categories: [`hair-ornament`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: `hair ornament`,
  },
  {
    prompt: `star hair ornament`,
    categories: [`hair-ornament`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: `hair ornament`,
  },
  {
    prompt: `tassel hair ornament`,
    categories: [`hair-ornament`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: `hair ornament`,
  },
  {
    prompt: `crown`,
    categories: [`hair-ornament`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: null,
  },
  {
    prompt: `tiara`,
    categories: [`hair-ornament`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: null,
  },
  {
    prompt: `diadem`,
    categories: [`hair-ornament`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: null,
  },
  {
    prompt: `headdress`,
    categories: [`hair-ornament`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: null,
  },
  {
    prompt: `maid headdress`,
    categories: [`hair-ornament`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: null,
  },
  {
    prompt: `veil`,
    categories: [`hair-ornament`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: null,
  },
  {
    prompt: `headband`,
    categories: [`hair-ornament`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: null,
  },
  {
    prompt: `hair bow`,
    categories: [`hair-bow`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: null,
  },
  {
    prompt: `red bow`,
    categories: [`hair-bow`],
    isEnableByDefault: false,
    colorCategory: `hair-bow`,
    color: `red`,
    suggests: null,
    parent: null,
  },
  {
    prompt: `pink bow`,
    categories: [`hair-bow`],
    isEnableByDefault: false,
    colorCategory: `hair-bow`,
    color: `pink`,
    suggests: null,
    parent: null,
  },
  {
    prompt: `orange bow`,
    categories: [`hair-bow`],
    isEnableByDefault: false,
    colorCategory: `hair-bow`,
    color: `orange`,
    suggests: null,
    parent: null,
  },
  {
    prompt: `brown bow`,
    categories: [`hair-bow`],
    isEnableByDefault: false,
    colorCategory: `hair-bow`,
    color: `brown`,
    suggests: null,
    parent: null,
  },
  {
    prompt: `yellow bow`,
    categories: [`hair-bow`],
    isEnableByDefault: false,
    colorCategory: `hair-bow`,
    color: `yellow`,
    suggests: null,
    parent: null,
  },
  {
    prompt: `green bow`,
    categories: [`hair-bow`],
    isEnableByDefault: false,
    colorCategory: `hair-bow`,
    color: `green`,
    suggests: null,
    parent: null,
  },
  {
    prompt: `aqua bow`,
    categories: [`hair-bow`],
    isEnableByDefault: false,
    colorCategory: `hair-bow`,
    color: `aqua`,
    suggests: null,
    parent: null,
  },
  {
    prompt: `blue bow`,
    categories: [`hair-bow`],
    isEnableByDefault: false,
    colorCategory: `hair-bow`,
    color: `blue`,
    suggests: null,
    parent: null,
  },
  {
    prompt: `purple bow`,
    categories: [`hair-bow`],
    isEnableByDefault: false,
    colorCategory: `hair-bow`,
    color: `purple`,
    suggests: null,
    parent: null,
  },
  {
    prompt: `black bow`,
    categories: [`hair-bow`],
    isEnableByDefault: false,
    colorCategory: `hair-bow`,
    color: `black`,
    suggests: null,
    parent: null,
  },
  {
    prompt: `grey bow`,
    categories: [`hair-bow`],
    isEnableByDefault: false,
    colorCategory: `hair-bow`,
    color: `grey`,
    suggests: null,
    parent: null,
  },
  {
    prompt: `white bow`,
    categories: [`hair-bow`],
    isEnableByDefault: false,
    colorCategory: `hair-bow`,
    color: `white`,
    suggests: null,
    parent: null,
  },
  {
    prompt: `hair ribbon`,
    categories: [`hair-ribbon`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: null,
  },
  {
    prompt: `red ribbon`,
    categories: [`hair-ribbon`],
    isEnableByDefault: false,
    colorCategory: `hair-ribbon`,
    color: `red`,
    suggests: null,
    parent: null,
  },
  {
    prompt: `pink ribbon`,
    categories: [`hair-ribbon`],
    isEnableByDefault: false,
    colorCategory: `hair-ribbon`,
    color: `pink`,
    suggests: null,
    parent: null,
  },
  {
    prompt: `orange ribbon`,
    categories: [`hair-ribbon`],
    isEnableByDefault: false,
    colorCategory: `hair-ribbon`,
    color: `orange`,
    suggests: null,
    parent: null,
  },
  {
    prompt: `brown ribbon`,
    categories: [`hair-ribbon`],
    isEnableByDefault: false,
    colorCategory: `hair-ribbon`,
    color: `brown`,
    suggests: null,
    parent: null,
  },
  {
    prompt: `yellow ribbon`,
    categories: [`hair-ribbon`],
    isEnableByDefault: false,
    colorCategory: `hair-ribbon`,
    color: `yellow`,
    suggests: null,
    parent: null,
  },
  {
    prompt: `green ribbon`,
    categories: [`hair-ribbon`],
    isEnableByDefault: false,
    colorCategory: `hair-ribbon`,
    color: `green`,
    suggests: null,
    parent: null,
  },
  {
    prompt: `aqua ribbon`,
    categories: [`hair-ribbon`],
    isEnableByDefault: false,
    colorCategory: `hair-ribbon`,
    color: `aqua`,
    suggests: null,
    parent: null,
  },
  {
    prompt: `blue ribbon`,
    categories: [`hair-ribbon`],
    isEnableByDefault: false,
    colorCategory: `hair-ribbon`,
    color: `blue`,
    suggests: null,
    parent: null,
  },
  {
    prompt: `purple ribbon`,
    categories: [`hair-ribbon`],
    isEnableByDefault: false,
    colorCategory: `hair-ribbon`,
    color: `purple`,
    suggests: null,
    parent: null,
  },
  {
    prompt: `black ribbon`,
    categories: [`hair-ribbon`],
    isEnableByDefault: false,
    colorCategory: `hair-ribbon`,
    color: `black`,
    suggests: null,
    parent: null,
  },
  {
    prompt: `grey ribbon`,
    categories: [`hair-ribbon`],
    isEnableByDefault: false,
    colorCategory: `hair-ribbon`,
    color: `grey`,
    suggests: null,
    parent: null,
  },
  {
    prompt: `white ribbon`,
    categories: [`hair-ribbon`],
    isEnableByDefault: false,
    colorCategory: `hair-ribbon`,
    color: `white`,
    suggests: null,
    parent: null,
  },
  {
    prompt: `hairband`,
    categories: [`hairband`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: null,
  },
  {
    prompt: `red hairband`,
    categories: [`hairband`],
    isEnableByDefault: false,
    colorCategory: `hairband`,
    color: `red`,
    suggests: null,
    parent: null,
  },
  {
    prompt: `pink hairband`,
    categories: [`hairband`],
    isEnableByDefault: false,
    colorCategory: `hairband`,
    color: `pink`,
    suggests: null,
    parent: null,
  },
  {
    prompt: `orange hairband`,
    categories: [`hairband`],
    isEnableByDefault: false,
    colorCategory: `hairband`,
    color: `orange`,
    suggests: null,
    parent: null,
  },
  {
    prompt: `brown hairband`,
    categories: [`hairband`],
    isEnableByDefault: false,
    colorCategory: `hairband`,
    color: `brown`,
    suggests: null,
    parent: null,
  },
  {
    prompt: `yellow hairband`,
    categories: [`hairband`],
    isEnableByDefault: false,
    colorCategory: `hairband`,
    color: `yellow`,
    suggests: null,
    parent: null,
  },
  {
    prompt: `green hairband`,
    categories: [`hairband`],
    isEnableByDefault: false,
    colorCategory: `hairband`,
    color: `green`,
    suggests: null,
    parent: null,
  },
  {
    prompt: `aqua hairband`,
    categories: [`hairband`],
    isEnableByDefault: false,
    colorCategory: `hairband`,
    color: `aqua`,
    suggests: null,
    parent: null,
  },
  {
    prompt: `blue hairband`,
    categories: [`hairband`],
    isEnableByDefault: false,
    colorCategory: `hairband`,
    color: `blue`,
    suggests: null,
    parent: null,
  },
  {
    prompt: `purple hairband`,
    categories: [`hairband`],
    isEnableByDefault: false,
    colorCategory: `hairband`,
    color: `purple`,
    suggests: null,
    parent: null,
  },
  {
    prompt: `black hairband`,
    categories: [`hairband`],
    isEnableByDefault: false,
    colorCategory: `hairband`,
    color: `black`,
    suggests: null,
    parent: null,
  },
  {
    prompt: `grey hairband`,
    categories: [`hairband`],
    isEnableByDefault: false,
    colorCategory: `hairband`,
    color: `grey`,
    suggests: null,
    parent: null,
  },
  {
    prompt: `white hairband`,
    categories: [`hairband`],
    isEnableByDefault: false,
    colorCategory: `hairband`,
    color: `white`,
    suggests: null,
    parent: null,
  },
  {
    prompt: `bow hairband`,
    categories: [`hairband`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: null,
  },
  {
    prompt: `frilled hairband`,
    categories: [`hairband`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: null,
  },
  {
    prompt: `lace-trimmed hairband`,
    categories: [`hairband`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: null,
  },
  {
    prompt: `lolita hairband`,
    categories: [`hairband`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: [`frilled hairband`],
    parent: null,
  },
  {
    prompt: `striped hairband`,
    categories: [`hairband`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: null,
  },
  {
    prompt: `two-tone hairband`,
    categories: [`hairband`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: null,
  },
  {
    prompt: `pointy ears`,
    categories: [`misc`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: null,
  },
  {
    prompt: `elf`,
    categories: [`misc`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: null,
  },
  {
    prompt: `gyaru`,
    categories: [`misc`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: null,
  },
  {
    prompt: `dark skin`,
    categories: [`misc`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: null,
  },
  {
    prompt: `single horn`,
    categories: [`misc`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: null,
  },
  {
    prompt: `mature female`,
    categories: [`misc`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: null,
  },
  {
    prompt: `curvy`,
    categories: [`misc`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: null,
  },
  {
    prompt: `loli`,
    categories: [`misc`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: null,
  },
  {
    prompt: `flat chest`,
    categories: [`breasts`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: null,
  },
  {
    prompt: `small breasts`,
    categories: [`breasts`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: null,
  },
  {
    prompt: `medium breasts`,
    categories: [`breasts`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: null,
  },
  {
    prompt: `large breasts`,
    categories: [`breasts`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: null,
  },
  {
    prompt: `huge breasts`,
    categories: [`breasts`],
    isEnableByDefault: false,
    colorCategory: null,
    color: null,
    suggests: null,
    parent: null,
  },
] as const;

const prompts = promptDefines.map(({ prompt }) => prompt);
const promptSetMutable = new Set(prompts);
export type Prompt = (typeof prompts)[number];
export const promptSet = promptSetMutable as ReadonlySet<Prompt>;

const categories = promptDefines.map(({ categories }) => categories).flat();
export type Category = (typeof categories)[number];
export const categorySet = new Set(categories) as ReadonlySet<Category>;

const colorNames = promptDefines.map(({ color }) => color);
export type ColorName = Exclude<(typeof colorNames)[number], null>;
const colorNameNullableSet = new Set(colorNames);
colorNameNullableSet.delete(null);
export const colorNameSet = colorNameNullableSet as ReadonlySet<ColorName>;

const colorCategories = promptDefines.map(({ colorCategory }) => colorCategory);
export type ColorCategory = Exclude<(typeof colorCategories)[number], null>;
const colorCategoryNullableSet = new Set(colorCategories);
colorCategoryNullableSet.delete(null);
export const colorCategorySet =
  colorCategoryNullableSet as ReadonlySet<ColorCategory>;

const parents = promptDefines.map(({ parent }) => parent);
export type Parent = Exclude<(typeof parents)[number], null>;
const parentNullableSet = new Set(parents);
parentNullableSet.delete(null);
export const parentSet = parentNullableSet as ReadonlySet<Parent>;

type PromptEnableInfo = { [K in Prompt]: boolean };
const defaultInfo = promptDefines.reduce(
  (a, { prompt, isEnableByDefault }) => ({ ...a, [prompt]: isEnableByDefault }),
  {},
) as PromptEnableInfo;

export const promptEnableInfoStore = map<PromptEnableInfo>(defaultInfo);

export const getDefine = (p: Prompt) =>
  promptDefines.filter(({ prompt }) => prompt === p)[0];

export const getDefinesByCategory = (c: Category) =>
  promptDefines.filter(({ categories }) =>
    (categories as readonly Category[]).includes(c),
  );

export const getDefinesByColorCategory = (c: ColorCategory) =>
  promptDefines.filter(({ colorCategory }) => colorCategory === c);

export const getDefinesHaveChildren = () =>
  promptDefines.filter(({ prompt }) => (parentSet as Set<unknown>).has(prompt));

export const getDefinesHaveParent = () =>
  promptDefines.filter(({ parent }) => parent);

export const getChildDefines = (parent: Prompt) =>
  promptDefines.filter(({ parent: p }) => p === parent);

export const getParentDefine = (child: Prompt) => {
  const childDefine = getDefine(child);
  if (!childDefine.parent) return null;
  return getDefine(childDefine.parent);
};
